-- Dijital kimlik QR guvenlik ve guncelleme gecmisi

alter table if exists public.hayvan_kimlikleri
  add column if not exists qr_dogrulama_token text;

create table if not exists public.hayvan_kimlik_guncelleme_gecmisi (
  id bigint generated by default as identity primary key,
  kimlik_id bigint not null references public.hayvan_kimlikleri (id) on delete cascade,
  hayvan_id bigint not null references public.hayvanlar (id) on delete cascade,
  guncelleyen_kullanici_id uuid references public.kullanicilar (id) on delete set null,
  onceki_pdf_url text,
  yeni_pdf_url text,
  onceki_qr_icerik text,
  yeni_qr_icerik text,
  not_ozeti text,
  olusturma_tarihi timestamptz not null default now()
);

create index if not exists idx_kimlik_gecmis_hayvan_tarih
  on public.hayvan_kimlik_guncelleme_gecmisi (hayvan_id, olusturma_tarihi desc);

alter table public.hayvan_kimlik_guncelleme_gecmisi enable row level security;

drop policy if exists "kimlik_gecmis_select_sahip" on public.hayvan_kimlik_guncelleme_gecmisi;
create policy "kimlik_gecmis_select_sahip"
  on public.hayvan_kimlik_guncelleme_gecmisi
  for select
  using (
    exists (
      select 1 from public.hayvanlar h
      where h.id = hayvan_id and h.sahibi_id = auth.uid()
    )
  );

drop policy if exists "kimlik_gecmis_select_veteriner" on public.hayvan_kimlik_guncelleme_gecmisi;
create policy "kimlik_gecmis_select_veteriner"
  on public.hayvan_kimlik_guncelleme_gecmisi
  for select
  using (
    exists (
      select 1
      from public.saglik_kayitlari sk
      where sk.hayvan_id = hayvan_id
        and sk.veteriner_id = auth.uid()
    )
    or exists (
      select 1
      from public.randevular r
      where r.hayvan_id = hayvan_id
        and r.veteriner_id = auth.uid()
    )
  );
